"use client";

import { useEffect, useMemo, useState } from "react";

export type ClientLanguage = "en" | "ar";

const STORAGE_KEY = "fitlift_client_language";
const EVENT_NAME = "fitlift-client-language-change";

type TranslationValue = string | ((params?: Record<string, string | number>) => string);

const translations = {
  en: {
    languageToggle: "ع",
    home: "Home",
    workouts: "Workouts",
    nutrition: "Nutrition",
    progress: "Progress",
    assessments: "Assessments",
    helpSupport: "Help & Support",
    logOut: "Log Out",
    openSettings: "Open dashboard settings",
    memberId: "Member ID",
    startDate: "Start Date",
    plan: ({ type }: Record<string, string | number> = {}) => `${type ?? ""} Plan`,
    expiredDaysAgo: ({ count }: Record<string, string | number> = {}) => `Expired ${count ?? 0} days ago`,
    daysLeft: ({ count }: Record<string, string | number> = {}) => `${count ?? 0} day${Number(count ?? 0) === 1 ? "" : "s"} left`,
    daysProgress: ({ remaining, total }: Record<string, string | number> = {}) => `${remaining ?? 0} / ${total ?? 0} days`,
    start: "Start",
    expires: "Expires",
    subscriptionExpired: "Your subscription has expired. Contact us to renew.",
    subscriptionExpiring: "Your subscription is expiring soon. Renew to keep access.",
    renewNow: "Renew Now",
    urgent: "URGENT",
    daysLeftShort: ({ count }: Record<string, string | number> = {}) => `${count ?? 0}D LEFT`,
    onlineWatching: "Online · Watching your progress",
    viewDashboard: "View Dashboard",
    gymUpdates: "Gym Updates",
    latestAnnouncements: "Latest Announcements",
    seeMore: "See more",
    seeLess: "See less",
    dashboardReady: "Your dashboard is ready for the first update",
    dashboardReadyBody: "As soon as your coach posts an announcement or new gym photo, it will land here.",
    todaysNutrition: "Today's Nutrition",
    mealsLogged: "Meals Logged",
    openNutrition: "Open Nutrition",
    copiedMembershipCode: "Membership code copied",
    copyMembershipCode: "Copy membership code",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    urgentBadge: "Urgent",
    goals: "Goals",
    assessmentsTitle: "Assessments",
    sharedFiles: "Shared Files",
    all: "All",
    assignedCoach: "Assigned Coach",
    noAssignedCoach: "Not assigned to a coach",
    assessmentsBody: "Body measurement requests, progress materials, and coach files live here.",
    loadingAssessments: "Loading assessments...",
    noAssessmentsYet: "No assessments yet",
    noAssessmentsBody: "As soon as your coach sends one, it will show up here with files and instructions.",
    pending: "Pending",
    submitted: "Submitted",
    reviewed: "Reviewed",
    instructions: "Instructions",
    requestedMeasurements: "Requested Measurements",
    due: "Due",
    download: "Download",
    fromCoach: ({ name }: Record<string, string | number> = {}) => `From: ${name ?? ""}`,
    workoutsTitle: "Your Workouts",
    thisWeek: "This Week",
    editPlan: "Edit Plan",
    todayLabel: "Today",
    weeklyProgress: "Weekly Progress",
    assignedWorkouts: "Assigned Workouts",
    addWorkout: "Add Workout",
    noWorkoutsYet: "No workouts yet",
    noWorkoutsBody: "Build your first workout and start tracking from here.",
    createWorkout: "Create Workout",
    currentTasks: "Current Tasks",
    manageTasks: "Manage Tasks",
    reset: "Reset",
    coachBadge: "Coach",
    finishWorkout: "Finish",
    actionUndone: "Action undone.",
    allTasksReset: "All tasks reset",
    editWeeklyPlan: "Edit Weekly Plan",
    done: "Done",
    savePlan: "Save Plan",
    editTasks: "Edit Tasks",
    low: "Low",
    medium: "Medium",
    high: "High",
    newTask: "New Task",
    addTask: "Add Task",
    saveTasks: "Save Tasks",
    cancel: "Cancel",
    save: "Save",
    workoutDone: "Done",
    workoutPending: "Pending",
    nutritionDemoBanner: "Demo preview: sample meals are shown so first-time clients can see what a complete nutrition day looks like.",
    kcalRemaining: "kcal remaining",
    closeGoalEditor: "Close goal editor",
    editNutritionGoals: "Edit nutrition goals",
    caloriesKcal: "Calories (kcal)",
    proteinG: "Protein (g)",
    carbsG: "Carbs (g)",
    fatG: "Fat (g)",
    saving: "Saving...",
    saveGoals: "Save Goals",
    logMeal: "Log a Meal",
    demoLabel: "demo",
    nutritionHelper: "Describe what you ate or tap a suggestion below — AI calculates macros instantly.",
    recent: "Recent",
    favorites: "Favorites",
    mealPlaceholder: "e.g. 200g grilled chicken with 1 cup brown rice...",
    describeMealAria: "Describe your meal for AI analysis",
    analyzingMeal: "Analyzing meal entry.",
    analyzeAndLogMeal: "Analyze and log meal",
    analyzing: "Analyzing...",
    analyzeAndLog: "Analyze & Log",
    todaysMeals: "Today's Meals",
    noMealsYet: "No meals logged yet. Your meals will appear here once you start tracking.",
    failedAnalyzeMeal: "Failed to analyze meal.",
    aiBusy: "AI meal analysis is temporarily busy right now. Please try again in a minute.",
    failedLoadProgressProfile: "Failed to load progress profile",
    failedSaveGoals: "Failed to save goals",
    nutritionGoalsUpdated: "Nutrition goals updated",
    photoUpload: "Photo Upload",
    couldntSaveMeal: "Couldn't save that meal.",
    mealLogged: ({ name }: Record<string, string | number> = {}) => `${name ?? "Meal"} logged.`,
    mealLoggedSuccess: ({ name }: Record<string, string | number> = {}) => `${name ?? "Meal"} logged successfully.`,
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    useQuickFood: ({ name }: Record<string, string | number> = {}) => `Use quick food ${name ?? ""}`,
    removeMealPhoto: "Remove selected meal photo",
    daysCount: ({ done, total, pct }: Record<string, string | number> = {}) => `${done ?? 0}/${total ?? 0} days (${pct ?? 0}%)`,
    markDoneDay: ({ day }: Record<string, string | number> = {}) => `Mark ${day ?? ""} as done`,
    unmarkDoneDay: ({ day }: Record<string, string | number> = {}) => `Unmark ${day ?? ""} as done`,
    homeEmptyTitle: "Let's build your first win",
    homeEmptyBody: "Demo previews make the dashboard feel real before your live data starts coming in.",
    homeEmptyBody2: "Start with a guided preview, then switch back to your live dashboard at any time.",
    tryDemoWorkout: "Try Demo Workout",
    tryDemoNutrition: "Try Demo Nutrition",
    meetCoach: ({ name }: Record<string, string | number> = {}) => `Meet ${name ?? ""}`,
    coachReady: "Your coach is ready to guide the first week.",
    welcomeFitLift: "Welcome to Fit & Lift. We'll use workouts, nutrition logs, and short check-ins to keep you moving without overload.",
    getStartedChecklist: "Get Started Checklist",
  },
  ar: {
    languageToggle: "EN",
    home: "الرئيسية",
    workouts: "التمارين",
    nutrition: "التغذية",
    progress: "التقدم",
    assessments: "التقييمات",
    helpSupport: "المساعدة والدعم",
    logOut: "تسجيل الخروج",
    openSettings: "افتح إعدادات الداشبورد",
    memberId: "كود العضوية",
    startDate: "تاريخ البداية",
    plan: ({ type }: Record<string, string | number> = {}) => `خطة ${type ?? ""}`,
    expiredDaysAgo: ({ count }: Record<string, string | number> = {}) => `الاشتراك انتهى من ${count ?? 0} يوم`,
    daysLeft: ({ count }: Record<string, string | number> = {}) => `فاضل ${count ?? 0} يوم`,
    daysProgress: ({ remaining, total }: Record<string, string | number> = {}) => `${remaining ?? 0} / ${total ?? 0} يوم`,
    start: "البداية",
    expires: "ينتهي",
    subscriptionExpired: "الاشتراك انتهى. كلمنا عشان تجدده.",
    subscriptionExpiring: "الاشتراك قرب يخلص. جدده عشان تفضل الصلاحية شغالة معاك.",
    renewNow: "جدّد دلوقتي",
    urgent: "مهم",
    daysLeftShort: ({ count }: Record<string, string | number> = {}) => `فاضل ${count ?? 0} يوم`,
    onlineWatching: "متابع معاك دلوقتي",
    viewDashboard: "شوف الداشبورد",
    gymUpdates: "تحديثات الجيم",
    latestAnnouncements: "آخر الإعلانات",
    seeMore: "شوف أكتر",
    seeLess: "شوف أقل",
    dashboardReady: "الداشبورد جاهز لأول تحديث",
    dashboardReadyBody: "أول ما الكوتش ينزل إعلان أو صورة جديدة، هتلاقيها هنا.",
    todaysNutrition: "تغذية النهارده",
    mealsLogged: "وجبات متسجلة",
    openNutrition: "افتح التغذية",
    copiedMembershipCode: "تم نسخ كود العضوية",
    copyMembershipCode: "انسخ كود العضوية",
    protein: "البروتين",
    carbs: "الكارب",
    fat: "الدهون",
    urgentBadge: "مهم",
    goals: "الأهداف",
    assessmentsTitle: "التقييمات",
    sharedFiles: "الملفات المشتركة",
    all: "الكل",
    assignedCoach: "المدرب المسؤول",
    noAssignedCoach: "لسه مفيش مدرب متعيّن ليك",
    assessmentsBody: "طلبات القياسات، ملفات المتابعة، وأي مواد يبعتهالك الكوتش هتلاقيها هنا.",
    loadingAssessments: "بنحمّل التقييمات...",
    noAssessmentsYet: "لسه مفيش تقييمات",
    noAssessmentsBody: "أول ما الكوتش يبعتلك تقييم، هينزل هنا مع الملفات والتعليمات.",
    pending: "معلّق",
    submitted: "مرفوع",
    reviewed: "تمت مراجعته",
    instructions: "التعليمات",
    requestedMeasurements: "القياسات المطلوبة",
    due: "الموعد المطلوب",
    download: "نزّل الملف",
    fromCoach: ({ name }: Record<string, string | number> = {}) => `من الكوتش: ${name ?? ""}`,
    workoutsTitle: "تمارينك",
    thisWeek: "الأسبوع ده",
    editPlan: "عدّل الخطة",
    todayLabel: "النهارده",
    weeklyProgress: "تقدم الأسبوع",
    assignedWorkouts: "التمارين المتحددة ليك",
    addWorkout: "أضف تمرين",
    noWorkoutsYet: "لسه مفيش تمارين",
    noWorkoutsBody: "ابدأ أول تمرين من هنا وخلي متابعتك ماشية معاك خطوة بخطوة.",
    createWorkout: "اعمل تمرين",
    currentTasks: "مهامك الحالية",
    manageTasks: "نظّم المهام",
    reset: "صفّرها",
    coachBadge: "الكوتش",
    finishWorkout: "أنهِ التمرين",
    actionUndone: "رجّعنا آخر خطوة.",
    allTasksReset: "اتصفّرت كل المهام.",
    editWeeklyPlan: "عدّل خطة الأسبوع",
    done: "تم",
    savePlan: "احفظ الخطة",
    editTasks: "عدّل المهام",
    low: "منخفض",
    medium: "متوسط",
    high: "عالي",
    newTask: "مهمة جديدة",
    addTask: "أضف مهمة",
    saveTasks: "احفظ المهام",
    cancel: "إلغاء",
    save: "حفظ",
    workoutDone: "تم",
    workoutPending: "مستني",
    nutritionDemoBanner: "دي معاينة تجريبية فيها وجبات مثال عشان تشوف يوم التغذية بيبقى شكله عامل إزاي قبل ما بياناتك الحقيقية تبدأ تظهر.",
    kcalRemaining: "سعر حراري متبقي",
    closeGoalEditor: "اقفل تعديل الأهداف",
    editNutritionGoals: "عدّل أهداف التغذية",
    caloriesKcal: "السعرات (kcal)",
    proteinG: "البروتين (g)",
    carbsG: "الكارب (g)",
    fatG: "الدهون (g)",
    saving: "جارٍ الحفظ...",
    saveGoals: "احفظ الأهداف",
    logMeal: "سجّل وجبة",
    demoLabel: "تجريبي",
    nutritionHelper: "اكتب أكلت إيه أو اختار اقتراح من تحت، والذكاء الاصطناعي هيحسب الماكروز فورًا.",
    recent: "الأحدث",
    favorites: "المفضلة",
    mealPlaceholder: "مثال: ٢٠٠ جم فراخ مشوية مع كوب رز بني...",
    describeMealAria: "اوصف وجبتك لتحليل الذكاء الاصطناعي",
    analyzingMeal: "بنحلل الوجبة دلوقتي.",
    analyzeAndLogMeal: "حلّل الوجبة وسجّلها",
    analyzing: "جارٍ التحليل...",
    analyzeAndLog: "حلّل وسجّل",
    todaysMeals: "وجبات النهارده",
    noMealsYet: "لسه مفيش وجبات متسجلة. أول ما تبدأ تضيف، هتظهر هنا.",
    failedAnalyzeMeal: "ماعرفناش نحلل الوجبة.",
    aiBusy: "تحليل الوجبات بالذكاء الاصطناعي مشغول شوية دلوقتي. جرّب بعد دقيقة.",
    failedLoadProgressProfile: "ماقدرناش نحمّل ملف التقدم.",
    failedSaveGoals: "ماقدرناش نحفظ الأهداف.",
    nutritionGoalsUpdated: "اتحدثت أهداف التغذية.",
    photoUpload: "رفع صورة",
    couldntSaveMeal: "ماقدرناش نحفظ الوجبة دي.",
    mealLogged: ({ name }: Record<string, string | number> = {}) => `اتسجلت ${name ?? "الوجبة"}.`,
    mealLoggedSuccess: ({ name }: Record<string, string | number> = {}) => `تم تسجيل ${name ?? "الوجبة"} بنجاح.`,
    breakfast: "فطار",
    lunch: "غدا",
    dinner: "عشا",
    snack: "سناك",
    useQuickFood: ({ name }: Record<string, string | number> = {}) => `استخدم الاختيار السريع ${name ?? ""}`,
    removeMealPhoto: "احذف صورة الوجبة المختارة",
    daysCount: ({ done, total, pct }: Record<string, string | number> = {}) => `${done ?? 0}/${total ?? 0} يوم (${pct ?? 0}%)`,
    markDoneDay: ({ day }: Record<string, string | number> = {}) => `علّم ${day ?? ""} كتم`,
    unmarkDoneDay: ({ day }: Record<string, string | number> = {}) => `شيل علامة التم من ${day ?? ""}`,
    homeEmptyTitle: "يلا نبدأ أول خطوة صح",
    homeEmptyBody: "المعاينات التجريبية بتخليك تشوف شكل الداشبورد من بدري قبل ما بياناتك الحقيقية تظهر.",
    homeEmptyBody2: "ابدأ بمعاينة سريعة، وبعدها ارجع للداشبورد الحي في أي وقت.",
    tryDemoWorkout: "جرّب تمرين تجريبي",
    tryDemoNutrition: "جرّب تغذية تجريبية",
    meetCoach: ({ name }: Record<string, string | number> = {}) => `اتعرف على ${name ?? ""}`,
    coachReady: "الكوتش جاهز يبتدي معاك أول أسبوع.",
    welcomeFitLift: "أهلاً بيك في فيت آند ليفت. هنتابع التمارين والتغذية والشيك إنات القصيرة بشكل يفضل مناسب ليك من غير ضغط.",
    getStartedChecklist: "قائمة البداية",
  },
} satisfies Record<ClientLanguage, Record<string, TranslationValue>>;

function readLanguage(): ClientLanguage {
  if (typeof window === "undefined") return "en";
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === "ar" ? "ar" : "en";
}

export function setClientLanguage(language: ClientLanguage) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, language);
  window.dispatchEvent(new CustomEvent(EVENT_NAME, { detail: language }));
}

export function useClientLanguage() {
  const [language, setLanguageState] = useState<ClientLanguage>("en");

  useEffect(() => {
    setLanguageState(readLanguage());

    const sync = () => setLanguageState(readLanguage());
    const onCustom = (event: Event) => {
      const detail = (event as CustomEvent<ClientLanguage>).detail;
      setLanguageState(detail === "ar" ? "ar" : "en");
    };

    window.addEventListener("storage", sync);
    window.addEventListener(EVENT_NAME, onCustom as EventListener);

    return () => {
      window.removeEventListener("storage", sync);
      window.removeEventListener(EVENT_NAME, onCustom as EventListener);
    };
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.lang = language;
  }, [language]);

  const t = useMemo(() => {
    const table = translations[language];
    return (key: keyof typeof translations.en, params?: Record<string, string | number>) => {
      const value = table[key];
      return typeof value === "function" ? value(params) : value;
    };
  }, [language]);

  return {
    language,
    t,
    setLanguage: setClientLanguage,
  };
}
