-- Table: calorie_logs
CREATE TABLE IF NOT EXISTS calorie_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  coach_id BIGINT REFERENCES coaches(id) ON DELETE CASCADE,
  meal TEXT NOT NULL,
  result JSONB NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('breakfast', 'lunch', 'dinner', 'snack')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Turn on Row Level Security
ALTER TABLE calorie_logs ENABLE ROW LEVEL SECURITY;

-- Note: Because we use the Supabase Service Role key in the backend APIs, 
-- DML operations will automatically bypass RLS.
