-- 1. Create client_tasks table
CREATE TABLE IF NOT EXISTS client_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  type TEXT NOT NULL, 
  title TEXT NOT NULL,
  status TEXT NOT NULL, 
  duration TEXT,
  assigned_by TEXT,
  coach_assigned BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Turn on Row Level Security
ALTER TABLE client_tasks ENABLE ROW LEVEL SECURITY;

-- 2. Create client_workouts table
CREATE TABLE IF NOT EXISTS client_workouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  coach_assigned BOOLEAN DEFAULT false,
  status TEXT NOT NULL, 
  duration TEXT,
  calories INTEGER,
  muscles JSONB, 
  difficulty TEXT,
  sets JSONB, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Turn on Row Level Security
ALTER TABLE client_workouts ENABLE ROW LEVEL SECURITY;
