-- Centralized progress profile for client dashboard state that is not derivable
-- from workouts or nutrition logs alone.
CREATE TABLE IF NOT EXISTS member_progress_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL UNIQUE REFERENCES members(id) ON DELETE CASCADE,
  body_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
  coach_goals JSONB NOT NULL DEFAULT '[]'::jsonb,
  personal_records JSONB NOT NULL DEFAULT '[]'::jsonb,
  wearable_connections JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_by_role TEXT,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE member_progress_profiles ENABLE ROW LEVEL SECURITY;

